import { User, UserType } from "../../models/User.js"
import userRepository, { UserRepository } from "../../repositories/UserRepository.js"
import { copyMatchingKeyValues } from "../../utils/Utils.js"

export class UserService {
    private userRepository: UserRepository

    constructor() {
        this.userRepository = userRepository
    }

    /**
     * ToDo:
     * We need to achieve just call save(obj). This save(obj) will internally
     * check if we should do update or create new. Normally this should be achieved by 
     * the ORM. But mongoose does not provide this functionality. We can implement this 
     * in BaseRepository. 
     * 
     * @param user
     * @returns 
     */
    async addUser(user: User): Promise<User> {
        let existingUser = await this.getUserByUserId(user.userId)
        if (existingUser == null) {
            return this.userRepository.save(user)
        }
        copyMatchingKeyValues(user, existingUser);
        (existingUser as any).save()
        return existingUser;
    }

    /**
     * User registration is currently only design for Recruiter, 
     * So we set the user.role as Recruiter 
     * ToDo: send a verify email(include a token)
     * @param user 
     * @returns 
     */
    async registerUser(user: User): Promise<User> {

        let existUser = await this.getUserByEmail(user.email);
        user.role = UserType.RECRUITER;
        if (!user.userId) {
            user.userId = user.email;
        }
        if (existUser == null) {
            return this.userRepository.save(user)
        }

        copyMatchingKeyValues(user, existUser);
        (existUser as any).save()
        return existUser;
    }

    /**
     * Get user by Id. The Id here is generated by mongodb
     * @param id 
     * @returns 
     */
    getUserById(id: string): Promise<User> {
        return this.userRepository.findById(id)
    }

    /**
     * Get user by userId. The userId is different from internal id generated by mongodb
     * @param userId 
     * @returns 
     */
    getUserByUserId(userId: string): Promise<User> {
        return this.userRepository.findOne({ userId: userId })
    }

    getUserByEmail(email: string): Promise<User> {
        return this.userRepository.findOne({ email })
    }

    getAnonymousUser(): Promise<User> {
        return this.userRepository.findOne({ userId: "anonymous" });
    }

    getAdminUser(): Promise<User> {
        return this.userRepository.findOne({ userId: "admin" });
    }

    async getAllUser(): Promise<User[]> {
        return this.userRepository.findAll();
    }
}

export default new UserService()